Revert "no? 1.11.1 then (same version maven-dependency-plugin 3.1.2 used)": unfortunately, 1.11.1 does not work with m-d-p 3.2.0 at all:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:analyze-only (analyse-dependency-usage) on project extract-tool: Execution analyse-dependency-usage of goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:analyze-only failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-dependency-plugin:3.2.0:analyze-only: java.lang.NoSuchMethodError: 'java.util.Set org.apache.maven.shared.dependency.analyzer.ProjectDependencyAnalysis.getTestArtifactsWithNonTestScope()'

This reverts commit 4f39aaa07c7e33c5df2b6641588960cca8de41cb.